### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by mathg** [Alxmerino/craft-locked-entries#1]
Hello! Thanks for this plugin, it does exactly what we want! Are you planning to release this for Craft 5 as well?

Thanks!

**Comment by Alxmerino** [comment]
Hi @mathg!

I'm planning to update it so it's compatible with Craft5, hopefully this week

**Comment by Alxmerino** [comment]
@mathg This should be available in the Plugin Store now https://plugins.craftcms.com/locked-entries?craft5

I'll mark this issue as closed now, but feel free to open another one if you come across any other issues
